name: Android Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 1.8 for the Android build
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '1.8'
          distribution: 'temurin'

      # Cache Gradle dependencies to speed up future builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Make Gradle wrapper executable
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Build the Android app with signing credentials from GitHub secrets
      - name: Build Android app
        run: ./gradlew app:bundleRelease
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          KEYSTORE: ${{ secrets.KEYSTORE }}

      # Upload the build artifact (app bundle) for download after workflow completion
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-bundle
          path: app/build/outputs/bundle/release/*.aab
